title: Computational Analytical Mechanics
author:
  name: Victor Bettachini
  email: "ask@for.it"
# author: Edgardo Palazzo
# email: epalazzo@fra.utn.edu.ar
description: >-
  DIIT UNLAM
baseurl: /ComputationalAnalyticalMechanics
# url: https://unlam.github.io/
url: https://frautn.github.io/
github_username: frautn

# Build settings
theme: minima

# plugins:
  # - jekyll-feed

# header_pages:
  # - about.md
  # - portfolio.md
